### ISSUE TITLE
counsel-M-x 使用下有问题

### ISSUE THREAD

**Issue by adispring** [xuchunyang/web-search.el#5]
M-x 只能输入 web-search ，web-search 命令后面不能输入参数。

M-x --> web-search haha 时，会出现下面的问题：
<img width="435" alt="screen shot 2017-11-15 at 10 53 54 am" src="https://user-images.githubusercontent.com/9584123/32816374-f797d54c-c97d-11e7-95e4-739dcdbc869c.png">

M-x --> web-search 时，会自动在search关键字处自动添加 web-search，如下： 
`Search Google: web-search`

**Comment by adispring** [comment]
<img width="245" alt="screen shot 2017-11-15 at 10 55 05 am" src="https://user-images.githubusercontent.com/9584123/32816475-736c2e98-c97e-11e7-811c-2f9ce5d0223d.png">

**Comment by xuchunyang** [comment]
> M-x 只能输入 web-search ，web-search 命令后面不能输入参数。

本来就不能，`M-x` 顶多就能传一个数字（Prefix Argument），不能传字符串。

> M-x --> web-search 时，会自动在search关键字处自动添加 web-search

这是个 Feature，会预输入光标下的词，要搜别的话，改之。

**Comment by xuchunyang** [comment]
因为一般我的需求都是搜索光标下的词或者 Symbol 或者选中区域的内容。

**Comment by adispring** [comment]
那这样的话，需要配合快捷键使用吧？

**Comment by xuchunyang** [comment]
都可以，快捷键或者 `M-x`。

在如何使用上，`web-search` 没任何特殊之处，跟别的 Emacs 命令一样，如 `describe-function` (`C-h f`)。

**Comment by adispring** [comment]
那是不是 README.md 需要更新一下？
```bash
;; From Emacs
M-x web-search puppies

# From the terminal
$ web-search puppies
```
